import 'package:drift_dev/api/migrations_native.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:ghpockit/core/database/database.dart';

import 'generated/schema.dart';

/// Every migration this app runs: v1 → v2 (`accounts`, W2 T3) and v2 → v3 (`categories`, W3 T5).
///
/// Golden rule 7 lets Phase 0–1 wipe the database instead of migrating it, and `settings` held nothing but a language preference — so the cheap path was
/// available and was refused. The reason is what this file is: W9 is an entire week of migration work, and a week of migration work needs an earlier schema
/// that actually exists on disk somewhere. Taking the exception would have meant the first migration Pockit ever writes being written in W9 against a
/// user's data, with no fixture to have practised on.
///
/// What is asserted here is the pair of properties a migration can break independently:
///
/// 1. **Shape** — a device upgrading from an older version lands on exactly the schema a device freshly installed at the new one gets.
///    `migrateAndValidate` reads `sqlite_schema` back and diffs it against `drift_schemas/drift_schema_vN.json`, so a forgotten `createIndex` fails here
///    rather than as a slow query in W8.
/// 2. **Data** — the old rows are still there afterwards, unchanged. A migration that produces a perfect schema and drops the user's settings is a
///    migration that passed shape and failed at the only thing the user notices.
/// 3. **Every step, in order** — a device that skipped a release walks v1 → v2 → v3 rather than jumping, which is what the `if (from < N)` chain buys.
///
/// The fixtures are the JSON dumps under `drift_schemas/`, regenerated by the two `drift_dev schema` commands in CLAUDE.md §9 on every bump. They are
/// committed, which is what makes v1 reproducible now that no code declares it any more.
void main() {
  late SchemaVerifier verifier;

  setUpAll(() {
    verifier = SchemaVerifier(GeneratedHelper());
  });

  test('migrates v1 → v2 into the schema a fresh v2 install has', () async {
    final connection = await verifier.startAt(1);
    final db = GPAppDatabase.forTesting(connection);

    // Throws `SchemaMismatch` on any difference — a missing table, a missing column, a differing constraint, or the index that `createTable` alone would
    // not have created.
    await verifier.migrateAndValidate(db, 2);

    await db.close();
  });

  test('carries v1 settings rows across the upgrade untouched', () async {
    final schema = await verifier.schemaAt(1);

    // Raw SQL against the raw handle, not `db.into(db.settingsTable)`. At this point the database genuinely *is* a v1 database, and `GPAppDatabase`
    // describes v2 — writing through it would be the current schema's opinion of an old row rather than the old row. This is the shape a v1 install
    // actually has on disk, which is the only fixture worth migrating.
    schema.rawDatabase.execute("INSERT INTO settings (key, value, updated_at) VALUES ('locale.selected', 'vi', 1757800000000)");

    final db = GPAppDatabase.forTesting(schema.newConnection());
    await verifier.migrateAndValidate(db, 2);

    final row = await (db.select(db.settingsTable)..where((t) => t.key.equals('locale.selected'))).getSingle();
    expect(row.value, 'vi');
    expect(row.updatedAt, 1757800000000);

    await db.close();
  });

  test('leaves the new accounts table present and empty after the upgrade', () async {
    final connection = await verifier.startAt(1);
    final db = GPAppDatabase.forTesting(connection);

    await verifier.migrateAndValidate(db, 2);

    // A v1 device has no accounts, so `accounts` must exist and be empty — not absent, and not back-filled with a placeholder row. Asserted because
    // `migrateAndValidate` checks shape only: a migration that created the table *and* seeded a row would pass the test above.
    expect(await db.select(db.accountsTable).get(), isEmpty);

    await db.close();
  });

  test('creates the accounts index on the upgrade path, not just on a fresh install', () async {
    final connection = await verifier.startAt(1);
    final db = GPAppDatabase.forTesting(connection);

    await verifier.migrateAndValidate(db, 2);

    // Stated separately from `migrateAndValidate` on purpose. An index is the one schema element whose absence changes no query result — only its cost —
    // so it is exactly the thing that rots silently. W8 benchmarks 50k rows against an index this asserts is really there.
    final indexes = await db.customSelect("SELECT name FROM sqlite_schema WHERE type = 'index' AND tbl_name = 'accounts'").get();

    expect(indexes.map((row) => row.read<String>('name')), contains('accounts_owner_id_is_archived'));

    await db.close();
  });

  test('migrates v2 → v3 into the schema a fresh v3 install has', () async {
    final connection = await verifier.startAt(2);
    final db = GPAppDatabase.forTesting(connection);

    await verifier.migrateAndValidate(db, 3);

    await db.close();
  });

  test('carries v2 accounts rows across the v3 upgrade untouched', () async {
    final schema = await verifier.schemaAt(2);

    // Raw SQL against the raw handle, for the same reason as the v1 case above: at this point the database genuinely is a v2 database.
    schema.rawDatabase.execute(
      'INSERT INTO accounts (id, owner_id, name, type, currency_code, initial_balance, is_archived, created_at, updated_at, version) '
      "VALUES ('a1', 'local', 'Ví tiền mặt', 'cash', 'VND', 1500000, 0, 1757800000000, 1757800000000, 1)",
    );

    final db = GPAppDatabase.forTesting(schema.newConnection());
    await verifier.migrateAndValidate(db, 3);

    final row = await (db.select(db.accountsTable)..where((t) => t.id.equals('a1'))).getSingle();
    expect(row.name, 'Ví tiền mặt');
    expect(row.initialBalance, 1500000);

    await db.close();
  });

  test('leaves the new categories table present and empty after the upgrade', () async {
    final connection = await verifier.startAt(2);
    final db = GPAppDatabase.forTesting(connection);

    await verifier.migrateAndValidate(db, 3);

    // **The seed is not a migration.** Seeding needs an owner and a clock, neither of which exists inside `onUpgrade`, and a migration that wrote rows
    // would also re-create the categories a user had deleted on the previous version. `CategorySeeder` runs at launch instead; this asserts the migration
    // stayed out of it, which `migrateAndValidate` cannot see because it checks shape only.
    expect(await db.select(db.categoriesTable).get(), isEmpty);

    await db.close();
  });

  test('creates both categories indexes on the upgrade path', () async {
    final connection = await verifier.startAt(2);
    final db = GPAppDatabase.forTesting(connection);

    await verifier.migrateAndValidate(db, 3);

    final indexes = await db.customSelect("SELECT name FROM sqlite_schema WHERE type = 'index' AND tbl_name = 'categories'").get();
    final names = indexes.map((row) => row.read<String>('name'));

    expect(names, contains('categories_owner_id_type'));
    // The unique one carries behaviour, not just cost: without it a second row can claim a seeded key, and the seeder's idempotency loses its second lock.
    expect(names, contains('categories_owner_id_name_key'));

    await db.close();
  });

  test('walks every step for a device that skipped a release', () async {
    // v1 → v3 in one go, which is what `if (from < N)` rather than `switch (from)` is written for and what nothing asserted until now. A user who installs
    // once and updates months later takes exactly this path.
    final connection = await verifier.startAt(1);
    final db = GPAppDatabase.forTesting(connection);

    await verifier.migrateAndValidate(db, 3);

    expect(await db.select(db.accountsTable).get(), isEmpty);
    expect(await db.select(db.categoriesTable).get(), isEmpty);

    await db.close();
  });
}
